<a href="https://colab.research.google.com/github/maciek6997/Basics2/blob/main/start/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([0,4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)

4.0

In [6]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [9]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [10]:
p = np.array([3,0,1])
q = np.array([0,4,2])

In [11]:
np.linalg.norm(p-q)

5.0990195135927845

In [12]:
X = np.array([[5,3],[3,9]])

Y = np.array([[1],[-1]])

In [13]:
X.dot(Y)

array([[ 2],
       [-6]])

In [16]:
Z = np.dot(X,Y)

In [17]:
Z.shape

(2, 1)

In [18]:
X = np.array([[2,-1,3],
              [3,1,0]])

Y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])

In [19]:
X.dot(Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [20]:
A = np.array([[2,4],[-1,3]])

In [22]:
round(np.linalg.det(A))

10

In [23]:
np.trace(A)

5

In [24]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
B = np.linalg.inv(A)

In [28]:
np.set_printoptions(precision=4,suppress=True)

A.dot(B)

array([[1., 0.],
       [0., 1.]])

In [29]:
B.dot(A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [30]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [31]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [32]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])

C = np.linalg.inv(A)

C.dot(B)

array([[1.],
       [2.]])