<a href="https://colab.research.google.com/github/maciek6997/Basics2/blob/main/start/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.19.5'

1D  Array

In [7]:
x = np.array([1,3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.3,2.3,1.4])

In [16]:
print(x)

[1.3 2.3 1.4]


In [17]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1,2],[-3,1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x.dtype

dtype('int64')

In [26]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [27]:
x.shape

(2, 3)

3D Array

In [34]:
x = np.array(
    [[[4,3,1],
     [3,1,2]],

       [[4,1,3],
      [4,2,1]],
     
     [[3,2,1],
      [4,3,2]]]
)


In [35]:
x.ndim

3

In [36]:
x.shape

(3, 2, 3)

Typy Danych


In [38]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [39]:
A = np.array([1.0,2.3,3.3])
A.dtype

dtype('float64')

In [41]:
A = np.array([1,2,3], dtype = 'float')

In [43]:
A = np.array([1,2,3], dtype = 'complex')

In [47]:
A = np.array([1.0,2.3,3.3], dtype='int')
A.dtype

dtype('int64')

In [48]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [50]:
A = np.array([24,120,230], dtype = np.uint8)

Tworzenie Tablic 

In [52]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
np.zeros(shape=(4,10),dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
np.ones(shape=(5,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.ones(shape=(5,5,),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.full(shape=(3,3,),fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [60]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
np.arange(start=100,stop=10,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [62]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [63]:
np.linspace(start=0,stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [64]:
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [70]:
A.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
A.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [72]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])

In [73]:
A+B

array([6, 0, 7, 4])

In [74]:
A - B 

array([0, 2, 1, 0])

In [75]:
A * B 

array([ 9, -1, 12,  4])

In [76]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [81]:
A + 3 

array([6, 4, 7, 5])

In [82]:
np.add(A,B)

array([6, 0, 7, 4])

In [84]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [78]:
A * 2 

array([6, 2, 8, 4])

In [79]:
abs(A)

array([3, 1, 4, 2])

In [80]:
A + 3*B

array([12, -2, 13,  8])

In [85]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [86]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [88]:
X = np.array([[1,3],[-2,0]])

Y = np.array([[6,0],[-1,2]])

In [89]:
 print(X*Y)

[[6 0]
 [2 0]]


In [90]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [91]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [92]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [93]:
X @ Y 

array([[  3,   6],
       [-12,   0]])

Liczby Pseudolosowe

In [99]:
np.random.seed(0)

In [100]:
np.random.randn()

1.764052345967664

In [101]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [102]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [103]:
np.random.rand()

0.1965823616800535

In [104]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [105]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [106]:
np.random.randint(10)

3

In [107]:
np.random.randint(low = 10,high = 101)

56

In [108]:
np.random.randint(low = 10,high = 101,size = 10 )

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [111]:
np.random.choice([4,2,1,3,5])

4

In [112]:
np.random.choice(['python','java','sql'])

'sql'

In [113]:
data = np.arange(10)

In [114]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.random.shuffle(data)

In [119]:
data

array([5, 6, 3, 9, 1, 0, 2, 8, 7, 4])

Funkcje Numpy

In [120]:
np.exp(1)

2.718281828459045

In [121]:
np.sqrt(9)

3.0

In [125]:
np.all([2,3,1])

True

In [127]:
np.any([0,0,0])

False

In [128]:
bool(0)

False

In [133]:
A = np.random.rand(5)
A

array([0.22126269, 0.1412639 , 0.09725993, 0.98404224, 0.26034093])

In [134]:
np.argmax(A)

3

In [135]:
A[np.argmax(A)]

0.9840422413641464

In [136]:
np.argmin(A)

2

In [137]:
A[np.argmin(A)]

0.09725992706317388

In [138]:
np.argsort(A)

array([2, 1, 0, 4, 3])

In [139]:
np.max(A)

0.9840422413641464

In [140]:
np.min(A)

0.09725992706317388

In [141]:
np.mean(A)

0.34083393722488087

In [142]:
np.median(A)

0.22126268518378278

In [143]:
np.std(A)

0.326695524195529

Indeksowanie i wycinanie 

In [144]:
A = np.arange(20)

In [145]:
A[2]

2

In [146]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [147]:
A[:2]

array([0, 1])

In [148]:
A[[0,2]]

array([0, 2])

In [149]:
A[-1]

19

In [150]:
A[10:15]

array([10, 11, 12, 13, 14])

In [152]:
A = A.reshape(4,5)

In [153]:
A[0]

array([0, 1, 2, 3, 4])

In [154]:
A[1]

array([5, 6, 7, 8, 9])

In [155]:
A[:,0]

array([ 0,  5, 10, 15])

In [157]:
A[:,-1]

array([ 4,  9, 14, 19])

In [159]:
A[1,1]

6

In [160]:
A[1,3]

8

In [162]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [165]:
 A[1,2] = 14 

In [166]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach 

In [168]:
for row in A: 
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [169]:
for row in A:
  print(row[0])

0
5
10
15


In [170]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [171]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [172]:
A.shape

(4, 5)

In [173]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [174]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [175]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [176]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Maski logiczne 

In [177]:
A = np.arange(start=-10,stop=10,step=0.5)

In [178]:
A = A.reshape(10,-1)

In [179]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [180]:
A > 0 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [181]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [183]:
A[A > 0 ]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [185]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [186]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [187]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [188]:
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])